### ISSUE TITLE
Can't install new site with Atlas extension

### ISSUE THREAD

**Issue by rob** [getflywheel/local-addon-atlas#21]
Running macOS 10.15.7 and Local 5.10.5+5403. Atlas extension 1.1.1.

Tried to create a new site using the Atlast extension and get an error almost right away:

<img width="532" alt="Screen Shot 2021-06-24 at 12 49 42" src="https://user-images.githubusercontent.com/503/123302416-b213a600-d4ea-11eb-81d5-74454fe72273.png">

Here's what the debug log says:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Applications/Local.app/Contents/MacOS/Local',
1 verbose cli   '/Users/rob/Library/Application Support/Local/addons/@getflywheel-local-addon-headless/node_modules/npx/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'create-next-app@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/Users/rob/.npm/_npx/39586',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v14.16.0
4 verbose npm-session 0f6f8c9ba80ba2d3
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/create-next-app 304ms (from cache)
8 silly pacote tag manifest for create-next-app@latest fetched in 405ms
9 verbose stack TypeError: cb.apply is not a function
9 verbose stack     at /Users/rob/Library/Application Support/Local/addons/@getflywheel-local-addon-headless/node_modules/npx/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
9 verbose stack     at FSReqCallback.oncomplete (fs.js:184:5)
10 verbose cwd /Users/rob/Local Sites/test
11 verbose Darwin 19.6.0
12 verbose argv "/Applications/Local.app/Contents/MacOS/Local" "/Users/rob/Library/Application Support/Local/addons/@getflywheel-local-addon-headless/node_modules/npx/node_modules/npm/bin/npm-cli.js" "install" "create-next-app@latest" "--global" "--prefix" "/Users/rob/.npm/_npx/39586" "--loglevel" "error" "--json"
13 verbose node v14.16.0
14 verbose npm  v5.1.0
15 error cb.apply is not a function
16 verbose exit [ 1, true ]
```

**Comment by maxkarkowski** [comment]
same problem here :(
